scheduler_site-main/scheduler_app/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', views.login_page, name='scheduler-login'),
    path('home/', views.home_page, name='scheduler-home'),
    path('courses/', views.course_page, name='scheduler-courses'),
    path('add-course/', views.add_course, name='scheduler-add-course'),
    path('delete-course/<str:name>', views.delete_course, name='scheduler-delete-course'),
    path('update-course/<str:name>', views.update_course, name='scheduler-update-course'),
    path('users/', views.user_page, name='scheduler-users'),
    path('user-info/<str:email>', views.user_info, name='scheduler-user'),
    path('add-user/', views.add_user, name='scheduler-add-user'),
    path('delete-user/<str:email>', views.delete_user, name='scheduler-delete-user'),
    path('logout_user/', views.logout_user, name="scheduler-logout-user"),
]

scheduler_site-main/scheduler_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scheduler_app.urls')),
]

scheduler_site-main/scheduler_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.base_user import BaseUserManager
import datetime
from scheduler_app.validators import validate_email


class UserManager(BaseUserManager):
    def create_user(self, email, password, account_type, **kwargs):
        validate_email(email)

        email = email.lower()

        # Do not require contact info/address upon account creation
        user = self.model(email=email, account_type=account_type, **kwargs)

        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password):
        return self.create_user(email, password, account_type=User.UserType.SUPERVISOR, is_staff=True,
                                is_superuser=True, is_active=True)


class User(AbstractUser):
    class UserType(models.TextChoices):
        SUPERVISOR = 'SU', 'Supervisor'
        INSTRUCTOR = 'IN', 'Instructor'
        TA = 'TA', 'TA'

    # Remove username that is inherited from AbstractUser
    username = None

    # Make email unique and set as new username for django auth
    email = models.EmailField('email', unique=True)
    USERNAME_FIELD = 'email'

    account_type = models.CharField(max_length=2, choices=UserType.choices, default=UserType.TA)
    phone_number = models.CharField(max_length=13, blank=True)
    state = models.CharField(max_length=2, blank=True)
    city = models.CharField(max_length=50, blank=True)
    address_line1 = models.CharField(max_length=50, blank=True)
    address_line2 = models.CharField(max_length=50, blank=True)
    zipcode = models.CharField(max_length=9, blank=True)

    # Requiring email here will cause parsing error when opening manage.py command line.
    # Instead, handle it in manager. Password verification also does not work properly if added here
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return self.email

    class Meta:
        ordering = ['account_type']


class CourseManager(models.Manager):
    def create_course(self, dpt, num, **kwargs):
        name = dpt + num

        # Course names are converted to uppercase (does not affect numbers or symbols).
        name = name.upper()

        course = self.model(name=name, dpt=dpt, num=num, **kwargs)
        course.save(force_insert=True)
        return course


class Course(models.Model):
    name = models.CharField(primary_key=True, max_length=30, unique=True)
    description = models.CharField(max_length=300, null=True, blank=True)
    term = models.CharField(max_length=20, null=True, blank=True)
    users = models.ManyToManyField(User, related_name='users-courses+')
    dpt = models.CharField(max_length=20)
    num = models.CharField(max_length=10)
    REQUIRED_FIELDS = []
    objects = CourseManager()

    def __str__(self):
        return self.name


class SectionManager(models.Manager):
    def create_section(self, section_number, course, meeting_start, meeting_end, meeting_days, **kwargs):
        if not section_number or not isinstance(section_number, str):
            raise TypeError('Section number must be provided to create a Section')

        if section_number.__len__() != 3:
            raise ValueError('Section number must be exactly 3 characters long')

        if not course or not isinstance(course, Course):
            raise TypeError('Course must be provided to create a Section')

        if not meeting_start or not isinstance(meeting_start, datetime.time):
            raise TypeError('Starting time is required to create a Section')

        if not meeting_end or not isinstance(meeting_end, datetime.time):
            raise TypeError('Ending time is required to create a Section')

        if meeting_days not in Section.MeetingDays.values:
            raise TypeError('Invalid meeting pattern')

        if meeting_start >= meeting_end:
            raise ValueError('A Section meeting cannot end until after it has started')

        try:
            section_list = Section.objects.filter(course=course)

            for rival in section_list:
                if rival.section_number == section_number:
                    raise ValueError('Two Sections with the same number cannot belong to the same Course')

        except Section.DoesNotExist:
            section_list = None

        section = self.model(section_number=section_number, course=course, meeting_start=meeting_start,
                             meeting_end=meeting_end, meeting_days=meeting_days, **kwargs)
        section.save()
        return section


class Section(models.Model):
    class SectionTypes(models.TextChoices):
        LAB = 'LAB', 'Lab'
        LECTURE = 'LEC', 'Lecture'

    class MeetingDays(models.TextChoices):
        MONDAY = 'M', 'Monday'
        TUESDAY = 'T', 'Tuesday'
        WEDNESDAY = 'W', 'Wednesday'
        THURSDAY = 'R', 'Thursday'
        FRIDAY = 'F', 'Friday'
        MON_WED = 'MW', 'Monday and Wednesday'
        TUE_THUR = 'TR', 'Tuesday and Thursday'

    section_number = models.CharField(max_length=3)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user+', on_delete=models.SET_NULL, null=True, blank=True)
    section_type = models.CharField(max_length=3, choices=SectionTypes.choices, default=SectionTypes.LECTURE)
    meeting_start = models.TimeField(null=True)
    meeting_end = models.TimeField(null=True)
    meeting_days = models.CharField(max_length=2, choices=MeetingDays.choices, default=MeetingDays.MON_WED)

    # A Section is required to have a section number, a Course, and a regular meeting schedule.
    REQUIRED_FIELDS = []

    objects = SectionManager()

    def __str__(self):
        return self.section_number

    class Meta:
        ordering = ['-section_type', 'section_number']


class SkillManager(models.Manager):
    def create_skill(self, name):
        if not name or not isinstance(name, str):
            raise TypeError('Skill name must be provided to create a Skill')

        skill = self.model(name=name)
        skill.save()
        return skill


class Skill(models.Model):
    name = models.CharField(max_length=100, unique=True)
    users = models.ManyToManyField(User, related_name='skills')

    # A Skill is required to have a name.
    REQUIRED_FIELDS = [name]

    objects = SkillManager()

    def __str__(self):
        return self.name

scheduler_site-main/scheduler_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.db import IntegrityError
from datetime import datetime
from django.db.models import Q
from operator import attrgetter

from scheduler_app.models import Course, User, Section, Skill
from django.core.exceptions import ValidationError, ObjectDoesNotExist


def login_page(request):
    # check for post request
    if request.method == 'POST':

        # Emails are stored in lowercase, so we make request email lowercase to make this
        # case-insensitive
        email = request.POST.get('email')

        if email is not None:
            email = email.lower()
        else:
            email = ""

        password = request.POST.get('password')

        # authenticate user
        user = authenticate(request, email=email, password=password)

        # if user is in database login and redirect to home if not reload page with error
        if user is not None:
            login(request, user)
            return redirect('scheduler-home')
        else:
            messages.error(request, 'Email or password is invalid.')
            return redirect('scheduler-login')

    if request.user.is_authenticated:
        return redirect("scheduler-home")

    # else a GET request, simply render page
    return render(request, 'scheduler_app/login.html')


def home_page(request):
    if not request.user.is_authenticated:
        messages.error(request, 'You must login to access the site.')
        return redirect('scheduler-login')

    if request.user.account_type == User.UserType.SUPERVISOR:
        # Pass the user's first name and empty list of assignments into the template.
        context = {
            'first_name': request.user.first_name,
            'assignments_list': None,
        }
    else:
        # Get the sections this user is assigned to organized by day.
        section_list = Section.objects.filter(user=request.user)

        if section_list.__len__() == 0:
            # Pass the user's first name and empty assignments list into the template.
            context = {
                'first_name': request.user.first_name,
                'assignments_list': None,
                'user': request.user
            }
        else:
            section_list = sorted(section_list, key=attrgetter('meeting_start'))

            monday_list = [section for section in section_list if (section.meeting_days == Section.MeetingDays.MONDAY) | (
                    section.meeting_days == Section.MeetingDays.MON_WED)]

            tuesday_list = [section for section in section_list if (section.meeting_days == Section.MeetingDays.TUESDAY) | (
                    section.meeting_days == Section.MeetingDays.TUE_THUR)]

            wednesday_list = [section for section in section_list if
                              (section.meeting_days == Section.MeetingDays.WEDNESDAY) | (
                                      section.meeting_days == Section.MeetingDays.MON_WED)]

            thursday_list = [section for section in section_list if
                             (section.meeting_days == Section.MeetingDays.THURSDAY) | (
                                     section.meeting_days == Section.MeetingDays.TUE_THUR)]

            friday_list = [section for section in section_list if section.meeting_days == Section.MeetingDays.FRIDAY]

            # Compile all section assignments into a dictionary corresponding to which day the section occurs during.
            assignments_list = {'Monday': monday_list, 'Tuesday': tuesday_list, 'Wednesday': wednesday_list,
                                'Thursday': thursday_list, 'Friday': friday_list}

            # Pass the user's first name and section assignments into the template.
            context = {
                'first_name': request.user.first_name,
                'assignments_list': assignments_list,
                'user': request.user,
                'current_day': datetime.today().strftime('%A')
            }

    return render(request, 'scheduler_app/home.html', context)


def course_page(request):
    if not request.user.is_authenticated:
        messages.error(request, 'You must login to access the site.')
        return redirect('scheduler-login')

    if request.method == 'GET':
        course_list = Course.objects.order_by('dpt', 'num')
        return render(request, "scheduler_app/courses.html", {"course_list": course_list, 'user': request.user})


def add_course(request):
    if not request.user.is_authenticated:
        messages.error(request, 'You must login to access the site.')
        return redirect('scheduler-login')

    # Get current user
    user = User.objects.filter(email=request.user.email)[0]

    # Supervisor only action
    if user.account_type != User.UserType.SUPERVISOR:
        messages.warning(request, "Access denied.")
        return redirect('scheduler-courses')

    if request.method == 'POST':
        dpt = ''
        num = ''
        try:
            dpt = request.POST['course_dpt'].strip()
            if not dpt.isalpha():
                raise ValueError

            num = request.POST['course_num'].strip()
            if not num.isdigit():
                raise ValueError

            description = request.POST['course_descr']
            course = Course.objects.create_course(dpt=dpt, num=num, description=description)
            messages.success(request, course.name + " has been added.")
            return redirect('scheduler-courses')
        except ValueError:
            messages.warning(request, "Requested course name is invalid.")
            return render(request, 'scheduler_app/add-course.html')
        except IntegrityError:
            messages.warning(request, dpt + num + " already exists.")
            return redirect('scheduler-courses')
    else:
        return render(request, 'scheduler_app/add-course.html')


def delete_course(request, name):
    if not request.user.is_authenticated:
        messages.error(request, 'You must login to access the site.')
        return redirect('scheduler-login')

    # Get current user
    user = User.objects.filter(email=request.user.email)[0]

    # Supervisor only action
    if user.account_type != User.UserType.SUPERVISOR:
        messages.warning(request, "Access denied.")
        return redirect('scheduler-courses')

    try:
        course = Course.objects.get(name=name)
        course.delete()
        messages.success(request, name + " has been deleted.")
        return redirect('scheduler-courses')
    except ObjectDoesNotExist:
        messages.warning(request, 'Course not found.')
        return redirect('scheduler-courses')


def update_course(request, name):
    if not request.user.is_authenticated:
        messages.error(request, 'You must login to access the site.')
        return redirect('scheduler-login')

    try:
        course = Course.objects.get(name=name)
    except ObjectDoesNotExist:
        messages.warning(request, 'Course not found.')
        return redirect('scheduler-courses')

    # Get current user
    user = User.objects.filter(email=request.user.email)[0]

    # Supervisor/instructor only
    if user.account_type == User.UserType.TA:
        messages.warning(request, "Access denied.")
        return redirect('scheduler-courses')

    # Instructor must belong to course in order to edit it
    if user.account_type == User.UserType.INSTRUCTOR and user not in course.users.all():
        messages.warning(request, 'Access denied.')
        return redirect('scheduler-courses')

    if request.method == 'POST':

        # Supervisor actions
        if user.account_type == User.UserType.SUPERVISOR:
            # Add user
            if 'add_user' in request.POST:
                user = User.objects.filter(email=request.POST['add_user'])[0]
                course.users.add(user)

            # Remove user from course and all sections they may belong to
            if 'remove_user' in request.POST:
                user = User.objects.filter(email=request.POST['remove_user'])[0]
                course.users.remove(user)
                sections = Section.objects.filter(course=course, user=user)
                for section in sections:
                    section.user = None
                    section.save()

            # Add section
            if 'section_type' in request.POST:
                # Verify all other data is there for the new section
                try:
                    if (
                        'section_number' not in request.POST or
                        'section_start' not in request.POST or
                        'section_end' not in request.POST or
                        'section_days' not in request.POST
                    ):
                        raise ValueError
                except ValueError:
                    messages.warning(request, "Invalid section request")
                else:
                    try:
                        # Create the new section
                        section_type = request.POST['section_type']
                        section_number = request.POST['section_number']
                        section_start = datetime.strptime(request.POST['section_start'], '%H:%M').time()
                        section_end = datetime.strptime(request.POST['section_end'], '%H:%M').time()
                        section_days = request.POST['section_days']
                        Section.objects.create_section(
                            section_number,
                            course,
                            section_start,
                            meeting_end=section_end,
                            meeting_days=section_days,
                            section_type=section_type
                        )
                    except ValueError as e:
                        messages.warning(request, str(e))

            # Remove section

scheduler_site-main/scheduler_app/templates/scheduler_app/add-course.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <title>Add Course</title>
</head>
    <body>
        <div class="entity-form">
            <form action="/add-course/" method="POST" autocomplete="off">
                <h1><b>Add New Course</b></h1>
                {% csrf_token %}
                <div class="inputs">
                    <label for="course_dpt">Course Department</label>
                    <p><input type="text" id="course_dpt" name="course_dpt" required></p>
                    <label for="course_num">Course Number</label>
                    <p><input type="text" id="course_num" name="course_num" required></p>
                    <label for="course_descr">Course Description</label>
                    <p><input type="text" id="course_descr" name="course_descr"></p>
                </div>
                <div class="form-buttons">
                    <button class="btn1 mt-1" type="submit" name="add_course">Add</button>
                    <button class="btn1 mt-1" type="submit" formmethod="get" formaction="/courses/" name="cancel" formnovalidate>Cancel</button>
                </div>
            </form>
        </div>
    </body>
</html>

scheduler_site-main/scheduler_app/templates/scheduler_app/courses.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
        <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
        <script src = "https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <title>Manage Courses</title>
    </head>
    <body>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <a class="navbar-brand" href="/home">TA Scheduler&#8482</a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item"><a class="nav-link" href="/home">Home</a></li>
                    <li class="nav-item"><a class="nav-link active" href="/courses">Courses</a></li>
                    <li class="nav-item"><a class="nav-link" href="/users">Users</a></li>
                </ul>
            </div>
            <form method="get" action="/user-info/{{ user.email }}">{% csrf_token %}
                <button class="btn btn-outline-info" type="submit">My Profile</button>
            </form>
             <form method="post" action="/logout_user/">{% csrf_token %}
                 <button class="btn btn-outline-danger" type="submit">Logout</button>
             </form>
        </nav>
        <div class="messages">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        <h2 class="manage-title">Course Management</h2>
        {% if user.get_account_type_display == 'Supervisor' %}
        <span><a href="/add-course" class="btn btn-primary add-entity">Add Course</a></span>
        {% endif %}
        <div class="table-responsive">
            <table class="table table-striped table-bordered" id="myTable">
                <thead>
                    <th>Course</th>
                    <th>Description</th>
                    <th>Sections</th>
                    <th>Users</th>
                    <th>Edit</th>
                    {% if user.get_account_type_display == 'Supervisor' %}
                    <th>Delete</th>
                    {% endif %}
                </thead>
                <tbody>
                    {% for course in course_list %}
                    <tr>
                        <td>{{ course.name }}</td>
                        <td>{{ course.description }}</td>
                        <td>
                            <table class="section-table">
                                <thead>
                                    <th>Type</th>
                                    <th>Number</th>
                                    <th>Days</th>
                                    <th>Start</th>
                                    <th>End</th>
                                    <th>Instructor</th>
                                </thead>
                                <tbody>
                                    {% for section in course.section_set.all %}
                                        <tr>
                                            <td>
                                              {{ section.section_type }}
                                            </td>
                                            <td>
                                              {{ section.section_number }}
                                            </td>
                                            <td>
                                              {{ section.meeting_days }}
                                            </td>
                                            <td>
                                              {{ section.meeting_start|time:'g:ia' }}
                                            </td>
                                            <td>
                                              {{ section.meeting_end|time:'g:ia' }}
                                            </td>
                                            <td>
                                              {{ section.user }}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </td>
                        <td>
                            <ul>
                                {% for user in course.users.all %}
                                    <li>{{ user.get_account_type_display }}: {{ user.email }}</li>
                                {% endfor %}
                            </ul>
                        </td>
                        {% if user.get_account_type_display == 'Supervisor' or user.get_account_type_display == 'Instructor' and user in course.users.all %}
                        <td><p data-placement="top" data-toggle="tooltip" title="Edit"><a href="/update-course/{{ course.name }}" class="btn btn-primary btn-xs" data-title="Edit" data-toggle="modal" data-target="#edit" ><span class="bi bi-pencil-fill"></span></a></p></td>
                        {% else %}
                        <td></td>
                        {% endif %}
                        {% if user.get_account_type_display == 'Supervisor' %}
                        <td><p data-placement="top" data-toggle="tooltip" title="Delete"><a href="/delete-course/{{ course.name }}" class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete" ><span class="bi bi-trash-fill"></span></a></p></td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </body>
</html>

scheduler_site-main/scheduler_app/templates/scheduler_app/user-info.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <title>Manage {{ user.email }}</title>
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <div class="messages top">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{message}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    </div>
    <h1 class="user-name">{{ user.first_name }} {{ user.last_name }}</h1>
    <div class="entity-form user-form">
        <form action="/courses/" method="POST" autocomplete="off">
                {% csrf_token %}
                <div class="info-inputs">
                    <label class="user-label" for="first_name">First Name</label>
                    <input type="text" id="first_name" name="first_name" placeholder="First name" value="{{ user.first_name }}">
                    <label class="user-label" for="last_name">Last Name</label>
                    <input type="text" id="last_name" name="last_name" placeholder="Last name" value="{{ user.last_name }}">
                    <label class="user-label" for="email">Email</label>
                    <input type="text" id="email" name="email" placeholder="Email" value="{{ user.email }}" readonly>
                    <label class="user-label" for="account_type">Account type</label>
                    <input type="text" id="account_type" name="account_type" placeholder="Account type" value="{{ user.get_account_type_display }}" readonly>
                    <label class="user-label" for="phone">Phone</label>
                    <input type="text" id="phone" name="phone" placeholder="Phone" value="{{ user.phone_number }}">
                    <h6>Address Information</h6>
                    <label class="user-label" for="city">City</label>
                    <input type="text" id="city" name="city" placeholder="City" value="{{ user.city }}">
                    <label class="user-label" for="state">State</label>
                    <input type="text" id="state" name="state" placeholder="State" value="{{ user.state }}" maxlength="2">
                    <label class="user-label" for="addr_1">Address Line 1</label>
                    <input type="text" id="addr_1" name="addr_1" placeholder="Address line 1" value="{{ user.address_line1 }}">
                    <label class="user-label" for="addr_2">Address Line 2</label>
                    <input type="text" id="addr_2" name="addr_2" placeholder="Address line 2" value="{{ user.address_line2 }}">
                    <label class="user-label" for="zipcode">Zipcode</label>
                    <input type="text" id="zipcode" name="zipcode" placeholder="Zipcode" value="{{ user.zipcode }}">
                    <h6>Skillset</h6>
                    <table class="manage-skill-table">
                        <tr>
                            <td>
                                <label for="skill-add">Add a Skill</label>
                            </td>
                            <td>
                                <select name="skill-add" id="skill-add">
                                    <option disabled selected value>Select a skill</option>
                                    {% for skill in skill_list %}
                                        <option value="{{ skill }}">{{ skill }}</option>
                                    {% endfor %}
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label for="skill-remove">Remove a Skill</label>
                            </td>
                            <td>
                                <select name="skill-remove" id="skill-remove">
                                    <option disabled selected value>Select a skill</option>
                                    {% for skill in user.skills.all %}
                                        <option value="{{ skill }}">{{ skill }}</option>
                                    {% endfor %}
                                </select>
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="form-buttons">
                    <button class="btn1 mt-1" type="submit" formmethod="post" formaction="/user-info/{{ user.email }}" name="update_user">Save</button>
                    <input type="button" class="btn1 mt-1" onclick="history.go(-1)" value="Back"/>
                </div>
        </form>
    </div>
</body>
</html>